sac/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show] do
    collection do
      put 'users/:id' => 'users#tornar_admin', :as => "tornar_admin"
      put 'users2/:id' => 'users#tirar_admin', :as => "tirar_admin"
      put 'users3/:id' => 'users#tornar_representante', :as => "tornar_representante"
      put 'users4/:id' => 'users#tirar_representante', :as => "tirar_representante"
    end
  end

  resources :orders do
    collection do
      delete 'destroy_old_data'
      put 'orders/:id' => 'orders#tornar_devolvida', :as => "tornar_devolvida"
      put 'orders2/:id' => 'orders#tornar_nao_devolvida', :as => "tornar_nao_devolvida"
      put 'orders3/:id' => 'orders#tem_que_pedir', :as => "tem_que_pedir"
      put 'orders4/:id' => 'orders#nao_tem_que_pedir', :as => "nao_tem_que_pedir"
    end
    resources :comments
  end

  resources :chamados do
    resources :comments
  end

  resources :areas
  get 'welcome/index'
  get 'admin/index'
  get 'admin/users'
  get 'admin/chamados'
  get 'admin/comentarios'
  get 'admin/pedir'

  get 'representante/index'

  root 'welcome#index'

end

sac/app/models/area.rb
class Area < ActiveRecord::Base
  validates :nome, presence: true
end

sac/app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :require_admin

  def index
    @areas = Area.all.order(id: :desc).paginate(page: params[:page], per_page: 10)
  end

  def show
    @area = Area.find(params[:id])
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    if @area.save
      flash[:success] = "Você criou a área com sucesso!"
      redirect_to areas_path
    else
      render 'new'
    end
  end

  def edit
    @area = Area.find(params[:id])
  end

  def update
    @area = Area.find(params[:id])
    if @area.update(area_params)
      flash[:success] = "Você editou a área com sucesso!"
      redirect_to areas_path
    else
      render 'edit'
    end
  end

  def destroy
    @area = Area.find(params[:id])
    if @area.destroy
      flash[:danger] = "Você excluiu a área com sucesso!"
      redirect_to areas_path
    end
  end

  private
    def area_params
      params.require(:area).permit(:nome)
    end

    def require_admin
      if !current_user.admin?
        flash[:danger] = "Somente administradores podem acessar esta área"
        redirect_to orders_path
      end
    end
end

sac/app/views/areas/_form.html.erb
<% if @area.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@area.errors.count, "erro") %> proibiu esta área de ser criada:</h2>
    <ul>
    <% @area.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@area, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :nome %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :nome, class: "form-control"%>
      </div>
    </div>
    <div class="col-sm-10" align="center">
      <%= link_to 'Voltar', areas_path, class: 'btn btn-default', align: 'left'%>
      <%= f.submit "Criar Área", class: "btn btn-success", align: 'right' %>
    </div>
  <% end %>
  </div>
</div>

sac/app/views/areas/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Editar área</div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

sac/app/views/areas/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Todas Áreas</h1>
  </div>
  <% @areas.each do |area| %>
  <li><%= area.nome %></li>
  <%= link_to 'Editar', edit_area_path(area) %>
  <%= link_to 'Deletar', area, method: :delete, data: { confirm: 'Tem certeza?' } %>
  <% end %>
</div>

sac/app/views/areas/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Nova área</div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>