sac/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show] do
    collection do
      put 'users/:id' => 'users#tornar_admin', :as => "tornar_admin"
      put 'users2/:id' => 'users#tirar_admin', :as => "tirar_admin"
      put 'users3/:id' => 'users#tornar_representante', :as => "tornar_representante"
      put 'users4/:id' => 'users#tirar_representante', :as => "tirar_representante"
    end
  end

  resources :orders do
    collection do
      delete 'destroy_old_data'
      put 'orders/:id' => 'orders#tornar_devolvida', :as => "tornar_devolvida"
      put 'orders2/:id' => 'orders#tornar_nao_devolvida', :as => "tornar_nao_devolvida"
      put 'orders3/:id' => 'orders#tem_que_pedir', :as => "tem_que_pedir"
      put 'orders4/:id' => 'orders#nao_tem_que_pedir', :as => "nao_tem_que_pedir"
    end
    resources :comments
  end

  resources :chamados do
    resources :comments
  end

  resources :areas
  get 'welcome/index'
  get 'admin/index'
  get 'admin/users'
  get 'admin/chamados'
  get 'admin/comentarios'
  get 'admin/pedir'

  get 'representante/index'

  root 'welcome#index'

end

sac/app/views/admin/chamados.html.erb
<div class="row" align="center">
  <%= link_to "Criar Área", new_area_path, class: 'btn btn-success btn-md'%>
</div>
<p>

</p>
<% if @chamados.exists? %>
  <h4> Seguem chamados não lidos </h4>
    <%= render 'chamados/chamados' %>
<% else %>
  <h4>Todas chamados foram lidos<h4>
<% end %>

sac/app/views/admin/comentarios.html.erb
<% if @comments.exists? %>
  <h4> Seguem os últimos comentários</h4>
    <div class="container">
        <div class="row col-md-12">
          <div align="center">
            <%= will_paginate @comments %>
          </div>
        <% @comments.each do |comment| %>
          <% if comment.commentable_type == "Order" %>
            <li>Garantia # <%=comment.commentable_id %> | Comentário: <%= comment.content %> em <%= comment.created_at %></li>
          <% else %>
            <li>Chamado # <%=comment.commentable_id %> | Comentário: <%= comment.content %> em <%= comment.created_at %></li>
          <% end %>
        <% end %>
      </div>
    </div>
<% else %>
  <h4>Não existem comentários<h4>
<% end %>

sac/app/views/admin/index.html.erb
<% if @orders.exists? %>
  <h4> Seguem solicitações não lidas </h4>
    <div class="container">
      <div class="row col-md-12">
        <%= render 'orders/orders' %>
      </div>
    </div>
<% else %>
  <h4>Todas solicitações foram lidas<h4>
<% end %>

sac/app/views/admin/pedir.html.erb
<div class="container">
    <div class="row col-md-12">
      <div class="row" align="center">
        <%= link_to "Solicitar garantia", new_order_path, class: 'btn btn-success btn-md'%>
      </div>
      <p>
      <% if @orders.count >= 1 %>
        <% if current_user.admin? %>
          <div class="row" align="center">
            <%= link_to 'Apagar garantias antigas', destroy_old_data_orders_path, method: :delete, class: 'btn btn-md btn-danger' %>
          </div>
          <p>
        <% end %>
        <div class="container" style="margin-top: 1%;">
          <div class="col-md-6 col-md-offset-3">
            <form role="form">
              <div class="row">
                <div class="form-group">
                  <div class="input-group">
                    <% if !current_user.admin? %>
                      <%= search_form_for @q do |f| %>
                      <%= f.search_field :referencia_cont, class: 'form-control', placeholder: 'Procurar por referência...' %>
                      <% end %>
                    <% else %>
                      <%= search_form_for @q do |f| %>
                      <%= f.search_field :referencia_or_representante_or_user_nome_cont, class: 'form-control', placeholder: 'Procurar por referência ou representante ou nome...' %>
                      <% end %>
                    <% end %>
                    <span class="input-group-btn">
                      <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></button>
                    </span>
                    </span>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
        <div class="row" align="center">
          <%= will_paginate @orders %>
        </div>
        <table class="table table-striped table-hover">
        <thead>
          <tr>
                <th style="text-align:center;">#</th>
                <th style="text-align:center;">Ref.</th>
                <th style="text-align:center;">Estado</th>
                <th style="text-align:center;">Devolvida</th>
                <% if current_user.representante? || current_user.admin? %>
                <th style="text-align:center;">Pedir</th>
                <% end %>
                <th style="text-align:center;"></th>
                <% if current_user.admin? %>
                <th style="text-align:center;">Nome</th>
                <th style="text-align:center;">Representante</th>
                <% end %>
            </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
        <% if current_user == order.user || current_user.admin? || current_user.nome == order.representante %>
          <tr>
            <td align="center"><%= order.id %></td>
            <td align="center" class="whatever"><%= order.referencia %></td>
            <td align="center">
              <% case order.estado %>
                <% when 'Solicitado' %>
                  <span class="label label-primary">Solicitado</span>
                <% when "Em processo de fabricação" %>
                  <span class="label label-primary">Em fabricação</span>
                <% when "Garantia pronta em nossas mãos" %>
                  <span class="label label-info">Garantia pronta</span>
                <% when "Enviada" %>
                  <span class="label label-success">Enviada</span>
              <% end %></td>
            <td align="center" valign="middle">
              <% if order.devolvida? %>
                <span class="label label-success">Sim</span>
              <% else %>
                <span class="label label-danger">Não</span>
              <% end %></td>
            <% if current_user.representante? || current_user.admin? %>
              <td align="center" valign="middle">
                <% if order.pedir? %>
                  <span class="label label-success">Sim</span>
                <% else %>
                  <span class="label label-danger">Não</span>
                <% end %></td>
            <% end %>
            <td align="center"><%= link_to 'Ver', order, class: 'btn btn-sm btn-primary'%>
              <% if current_user.admin? %>
                <%= link_to 'Editar', edit_order_path(order), class: 'btn btn-sm btn-primary'%></td>
            <td align="center"><%= order.user.nome %></td>
            <td align="center"><%= order.representante %></td>
            <% end %>
          </tr>
        <% end %>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <h4>Você ainda não possui solicitações!</h4>
    <% end %>
  </div>
</div>

sac/app/views/admin/users.html.erb
<h4 align="center"> Todos os usuários </h4>
<div align="center">
    <div class="container">
        <div class="row col-md-12">
        <div align="center">
          <%= will_paginate @users %>
        </div>
        <table class="table table-striped table-hover">
        <thead>
          <tr>
                <th style="text-align:center;">#</th>
                <th style="text-align:center;">Email</th>
                <th style="text-align:center;">Nome</th>
                <th style="text-align:center;">Admin</th>
                <th style="text-align:center;">Repres.</th>
                <th style="text-align:center;"></th>
            </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td align="center"><%= user.id %></td>
            <td align="center"><%= user.email %></td>
            <td align="center"><%= user.nome %></td>
            <td align="center"><% if user.admin? %> <span class="label label-success">Sim</span> <% else %> <span class="label label-danger">Não</span> <% end %> </td>
            <td align="center"><% if user.representante? %> <span class="label label-success">Sim</span> <% else %> <span class="label label-danger">Não</span> <% end %> </td>
            <td align="center"><%= link_to 'Ver', user, class: 'btn btn-sm btn-primary'%></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>
    </div>
</div>