sac/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show] do
    collection do
      put 'users/:id' => 'users#tornar_admin', :as => "tornar_admin"
      put 'users2/:id' => 'users#tirar_admin', :as => "tirar_admin"
      put 'users3/:id' => 'users#tornar_representante', :as => "tornar_representante"
      put 'users4/:id' => 'users#tirar_representante', :as => "tirar_representante"
    end
  end

  resources :orders do
    collection do
      delete 'destroy_old_data'
      put 'orders/:id' => 'orders#tornar_devolvida', :as => "tornar_devolvida"
      put 'orders2/:id' => 'orders#tornar_nao_devolvida', :as => "tornar_nao_devolvida"
      put 'orders3/:id' => 'orders#tem_que_pedir', :as => "tem_que_pedir"
      put 'orders4/:id' => 'orders#nao_tem_que_pedir', :as => "nao_tem_que_pedir"
    end
    resources :comments
  end

  resources :chamados do
    resources :comments
  end

  resources :areas
  get 'welcome/index'
  get 'admin/index'
  get 'admin/users'
  get 'admin/chamados'
  get 'admin/comentarios'
  get 'admin/pedir'

  get 'representante/index'

  root 'welcome#index'

end

sac/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SAC Paulo Carraro" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "SAC Paulo Carraro", root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
          <li><%= link_to "Garantias", orders_path %></li>
          <li><%= link_to "Chamados", chamados_path %></li>
            <% if current_user.representante? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Representante <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to representante_index_path do %>
                      Solicitações não lidas <span class="badge"><%= Order.all.where(:representante => current_user.nome, :read => false).count %></span></li>
                    <% end %>
              </ul>
            </li>
            <% end %>
            <% if current_user.admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Administração <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to admin_index_path do %>
                      Solicitações não lidas <span class="badge"><%= Order.all.where(:read => false).count %></span></li>
                    <% end %>
                <li><%= link_to admin_pedir_path do %>
                      Garantias para pedir <span class="badge"><%= Order.all.where(:pedir => true, :estado => "Solicitado").count %></span></li>
                    <% end %>
                <li><%= link_to admin_chamados_path do %>
                      Chamados não lidos <span class="badge"><%= Chamado.all.where(:read => false).count %></span></li>
                    <% end %>
                <li><%= link_to "Comentários", admin_comentarios_path %></li>
                <li><%= link_to "Usuários", admin_users_path %></li>
              </ul>
            </li>
            <% end %>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <%= current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Alterar dados", edit_user_registration_path %></li>
                <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
      </nav>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Paulo Carraro <%=Time.now.year%></p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>