sac/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show] do
    collection do
      put 'users/:id' => 'users#tornar_admin', :as => "tornar_admin"
      put 'users2/:id' => 'users#tirar_admin', :as => "tirar_admin"
      put 'users3/:id' => 'users#tornar_representante', :as => "tornar_representante"
      put 'users4/:id' => 'users#tirar_representante', :as => "tirar_representante"
    end
  end

  resources :orders do
    collection do
      delete 'destroy_old_data'
      put 'orders/:id' => 'orders#tornar_devolvida', :as => "tornar_devolvida"
      put 'orders2/:id' => 'orders#tornar_nao_devolvida', :as => "tornar_nao_devolvida"
      put 'orders3/:id' => 'orders#tem_que_pedir', :as => "tem_que_pedir"
      put 'orders4/:id' => 'orders#nao_tem_que_pedir', :as => "nao_tem_que_pedir"
    end
    resources :comments
  end

  resources :chamados do
    resources :comments
  end

  resources :areas
  get 'welcome/index'
  get 'admin/index'
  get 'admin/users'
  get 'admin/chamados'
  get 'admin/comentarios'
  get 'admin/pedir'

  get 'representante/index'

  root 'welcome#index'

end

sac/app/models/chamado.rb
class Chamado < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable

  validates :assunto, presence: true
  validates :descricao, presence: true
end

sac/app/controllers/chamados_controller.rb
class ChamadosController < ApplicationController

  before_action :require_same_user, only: [:show]

  def index
    if !current_user.admin? && !current_user.representante?
      @chamados = Chamado.all.where(:user => current_user).order(id: :desc).paginate(page: params[:page], per_page: 10)
    else
      @chamados = Chamado.all.order(id: :desc).paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    @chamado = Chamado.find(params[:id])
    @commentable = @chamado
    @comments = @commentable.comments
    @comment = Comment.new
    if current_user.admin? and !@chamado.read
      flash[:success] = "Você leu o chamado!"
      @chamado.read = true
      @chamado.save
    end
  end

  def new
    @chamado = Chamado.new
  end

  def create
    @chamado = Chamado.new(chamado_params)
    @chamado.user = current_user
    if @chamado.save
      flash[:success] = "Você abriu o chamado com sucesso!"
      redirect_to chamados_path
    else
      render 'new'
    end
  end

  def edit
    @chamado = Chamado.find(params[:id])
  end

  def update
    @chamado = Chamado.find(params[:id])
    if @chamado.update(chamado_params)
      flash[:success] = "Você atualizou o chamado com sucesso!"
      redirect_to chamados_path(@chamado)
    else
      render 'edit'
    end
  end

  def destroy
    @chamado = Chamado.find(params[:id])
    if @chamado.destroy
      flash[:danger] = "Você excluiu o chamado com sucesso!"
      redirect_to chamados_path
    end
  end

  private
    def chamado_params
      params.require(:chamado).permit(:area, :assunto, :descricao, :estado)
    end

    def require_same_user
      @chamado = Chamado.find(params[:id])
      if !current_user.admin? && current_user != @chamado.user
        flash[:danger] = "Você não pode acessar esta área"
        redirect_to orders_path
      end
    end
end

sac/app/views/chamados/_chamados.html.erb
<% @chamados.each do |chamado| %>
<% if current_user == chamado.user || current_user.admin? %>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Chamado # <%=chamado.id %></h3>
  </div>
  <div class="panel-body">
    <p>
    <li>Área: <%= chamado.area %></li>
    <li>Assunto: <%= chamado.assunto %></li>
    <li>Descrição: <%= chamado.descricao %></li>
    <li>Estado:
      <% case chamado.estado %>
        <% when 'Aberto' %>
          <span class="label label-primary">Aberto</span></li>
        <% when "Em processo de resolução" %>
          <span class="label label-success">Em processo de resolução</span></li>
        <% when "Fechado" %>
          <span class="label label-default">Fechado</span></li>
      <% end %>
    </p>
    <%= link_to 'Editar', edit_chamado_path(chamado), class: 'btn btn-sm btn-primary' %>
    <%= link_to 'Deletar', chamado, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-sm btn-danger' %>
    <%= link_to 'Ver', chamado, class: 'btn btn-sm btn-primary'%>
    <% if current_user.admin? %>
    Chamado aberto por: <%= chamado.user.nome %> | Email: <%= chamado.user.email %>
    <% end %>
  </div>
</div>
<% end %>
<% end %>

sac/app/views/chamados/_form.html.erb
<% if @chamado.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@chamado.errors.count, "erro") %> proibiu/proibiram este chamado ser aberto:</h2>
    <ul>
    <% @chamado.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@chamado, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :area %>
      </div>
      <div class="col-sm-10">
        <%= f.collection_select(:area, Area.all, :nome, :nome, {:prompt=>true}, {:class=>'form-control'})%>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :assunto %>
      </div>
      <div class="col-sm-10">
        <%= f.text_field :assunto, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :descricao %>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :descricao, class: "form-control", rows: "5"%>
      </div>
    </div>
    <% if current_user.admin? %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :estado %>
      </div>
      <div class="col-sm-10">
        <%= f.select(:estado, ['Aberto', 'Em processo de resolução', 'Fechado'], {}, { :class => 'form-control' }) %>
      </div>
    </div>
    <% end %>
    <div class="col-sm-10" align="center">
      <%= link_to 'Voltar', chamados_path, class: 'btn btn-default', align: 'left'%>
      <%= f.submit "Abrir", class: "btn btn-success", align: 'right' %>
    </div>
  <% end %>
</div>
</div>

sac/app/views/chamados/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Editar chamado</div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

sac/app/views/chamados/index.html.erb
<div class="container">
  <div class="row col-md-12">
    <div class="row" align="center">
      <%= link_to "Abrir chamado", new_chamado_path, class: 'btn btn-success btn-md'%>
    </div>
    <p>
    <% if @chamados.count >= 1 %>
      <%= render 'chamados' %>
    <% else %>
      <h4> Você ainda não possui chamados! </h4>
    <% end %>
  </div>
</div>

sac/app/views/chamados/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Abrir chamado</div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

sac/app/views/chamados/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Chamado # <%= @chamado.id %></h3>
  </div>
  <div class="panel-body">
    <li>Área: <%= @chamado.area %></li>
    <li>Assunto: <%= @chamado.assunto %></li>
    <li>Descrição: <%= @chamado.descricao %></li>
    <p><%= render 'comments/comments' %>
    <%= render 'comments/form' %></p>
  </div>
</div>